### ISSUE TITLE
Scanning for ServiceLoader fails with Java 10

### ISSUE THREAD

**Issue by sandermak** [moditect/moditect#64]
When I enable the `addServiceUses` configuration, the plugin fails on Java 10/11 with this root cause  exception:

```
Caused by: java.lang.IllegalArgumentException
	at org.moditect.internal.shaded.asm.ClassReader.<init>(Unknown Source)
	at org.moditect.internal.shaded.asm.ClassReader.<init>(Unknown Source)
	at org.moditect.internal.shaded.asm.ClassReader.<init>(Unknown Source)
	at org.moditect.internal.analyzer.ServiceLoaderUseScanner.getUsedServices(ServiceLoaderUseScanner.java:60)
	at org.moditect.internal.analyzer.ServiceLoaderUseScanner.lambda$getUsedServices$1(ServiceLoaderUseScanner.java:47)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:578)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.moditect.internal.analyzer.ServiceLoaderUseScanner.getUsedServices(ServiceLoaderUseScanner.java:47)
	at org.moditect.commands.GenerateModuleInfo.updateModuleInfo(GenerateModuleInfo.java:262)
	at org.moditect.commands.GenerateModuleInfo.run(GenerateModuleInfo.java:201)
	at org.moditect.mavenplugin.generate.ModuleInfoGenerator.generateModuleInfo(ModuleInfoGenerator.java:131)
	at org.moditect.mavenplugin.add.AddModuleInfoMojo.getModuleInfoSource(AddModuleInfoMojo.java:310)
	at org.moditect.mavenplugin.add.AddModuleInfoMojo.execute(AddModuleInfoMojo.java:150)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

Possibly a newer version of ASM should be shaded?

**Comment by gunnarmorling** [comment]
Thanks for this report. Any chance you build ModiTect from source using a newer version of ASM (I haven't checked with ASM recently what their latest version is) and try whether that does the trick?

**Comment by sandermak** [comment]
Just tried it, bumping the version to 6.2.1 did the trick! There was a breaking change in a constant though, in `ModuleInfoCompiler` the `V1_9` constant needs to be changed to `V9`.

**Comment by gunnarmorling** [comment]
Cool, thanks for exploring! Would you be interested in sending a PR with
the fix? I suppose the breakage is in the realm of what to expect, as,
IIRC, we were using a preview version of ASM.

**Comment by sandermak** [comment]
I would, but given that the build now breaks on the `integrationtest` project, I'm not sure where and how to proceed. If I find the time I'll dig further.

**Comment by sandermak** [comment]
Ok, now it succeeds, probably failed earlier because I tried the `V10`/`V11` options as well. Will create a PR!
