### ISSUE TITLE
jlink: Error reading module

### ISSUE THREAD

**Issue by rendaw** [moditect/moditect#92]
I got the error
```
[ERROR] Failed to execute goal org.moditect:moditect-maven-plugin:1.0.0.Beta2:create-runtime-image (create-runtime-image) on project shoedemo: Execution create-runtime-image of goal org.moditect:moditect-maven-plugin:1.0.0.Beta2:create-runtime-image failed: Execution of jlink failed -> [Help 1]
```

with a bit above it:
```
[DEBUG] Error: Error reading module: /home/andrew/temp/ren/shoedemo2/app/target/modules/guava-27.0.1-jre.jar
```

and traceback:
```
Caused by: java.lang.RuntimeException: Execution of jlink failed
    at org.moditect.internal.command.ProcessExecutor.run (ProcessExecutor.java:68)
    at org.moditect.commands.CreateRuntimeImage.runJlink (CreateRuntimeImage.java:114)
    at org.moditect.commands.CreateRuntimeImage.run (CreateRuntimeImage.java:68)
    at org.moditect.mavenplugin.image.CreateRuntimeImageMojo.execute (CreateRuntimeImageMojo.java:114)
```

The actual error is obscured (it seems like other similar errors are also hidden by jlink and people are working to expose them one by one: https://bugs.openjdk.java.net/browse/JDK-8204256).

To find the real cause you need the undocumented `-J-Djlink.debug=true` flag:

```
$ /usr/lib/jvm/java-11-openjdk/bin/jlink --verbose -J-Djlink.debug=true --add-modules c...o --module-path /.../app/target/modules:/usr/lib/jvm/java-11-openjdk/jmods --output /.../app/target/jlink-image-linux-x64
Error: Error reading module: /.../app/target/modules/guava-27.0.1-jre.jar
java.lang.module.FindException: Error reading module: /.../app/target/modules/guava-27.0.1-jre.jar
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:349)
	at java.base/jdk.internal.module.ModulePath.scanDirectory(ModulePath.java:283)
	at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:231)
	at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:189)
	at java.base/jdk.internal.module.ModulePath.find(ModulePath.java:153)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.newModuleFinder(JlinkTask.java:440)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.initJlinkConfig(JlinkTask.java:371)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:268)
	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:54)
	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)
Caused by: java.lang.module.InvalidModuleDescriptorException: Package com.google.common not found in module
	at java.base/jdk.internal.module.ModuleInfo.invalidModuleDescriptor(ModuleInfo.java:1092)
	at java.base/jdk.internal.module.ModuleInfo.doRead(ModuleInfo.java:325)
	at java.base/jdk.internal.module.ModuleInfo.read(ModuleInfo.java:132)
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:651)
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:330)
	... 9 more
```

While this isn't a moditect issue, since this project is all about working around upstream design issues perhaps this too could be worked around to improve the jmps experience.

And if I can piggyback on this :) I was confused by the docs regarding `add-module-info` - jars modularized this way can't be used except with the runtime image goal right?  Since they're distinct goals I thought there might be some way of using it as is but my search came up empty.  Clarifying its use case would be a tremendous help to people like me.

**Comment by gunnarmorling** [comment]
> While this isn't a moditect issue, since this project is all about working around upstream design issues perhaps this too could be worked around to improve the jmps experience.

So have you added the module descriptor for Guava yourself? Or does it come with one already? In case of the former you'd have to check your add-module-info config to ensure you inject a correct descriptor. In case of the latter there's not much we could do about it, other than making sure that error is visible by default.

> jars modularized this way can't be used except with the runtime image goal right?

You can use them in any scenario where you want to run your application with JPMS and not using the dependencies as automatic modules for some reason. Realistically, jlink images are the most relevant use case for that, as otherwise you just could use the dependencies as automatic modules which doesn't need any alteration. Automatic modules don't work with jlink, though.

**Comment by rendaw** [comment]
> other than making sure that error is visible by default.

Right, to be clear this issue is about making the actual cause of the failure visible by default.

> You can use them in any scenario where you want to run your application with JPMS and not using the dependencies as automatic modules for some reason.

If I take dependency `reflections` for instance and give it module name `org.reflections.reflections` with `add-module-info` the build fails because maven won't use the jar with `module-info.class` and thus javac can't resolve `org.reflections.reflections`.  It doesn't seem like there's a way to run your application with JPMS since the build won't even complete.
